USE [master]
GO

/****** Object:  Database [DBStrahPOLYKOV]    Script Date: 29.01.2025 16:16:51 ******/
DROP DATABASE [DBStrahPOLYKOV]
GO

/****** Object:  Database [DBStrahPOLYKOV]    Script Date: 29.01.2025 16:16:51 ******/
CREATE DATABASE [DBStrahPOLYKOV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBStrahPOLYKOV', FILENAME = N'/var/opt/mssql/data/DBStrahPOLYKOV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DBStrahPOLYKOV_log', FILENAME = N'/var/opt/mssql/data/DBStrahPOLYKOV_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBStrahPOLYKOV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET  MULTI_USER 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBStrahPOLYKOV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBStrahPOLYKOV] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBStrahPOLYKOV] SET QUERY_STORE = ON
GO

ALTER DATABASE [DBStrahPOLYKOV] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DBStrahPOLYKOV] SET  READ_WRITE 
GO

